### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by andysturrock** [drewnoakes/msgpack-strict#1]
When I build this, the following tests fail:
HandlesNestedComplexTypes
HandlesReadOnlyListProperty
ThrowsOnIncorrectDataType
ThrowsOnMissingField
UsesDefaultValuesIfNotInMessage

Is that expected at the moment?  Ie work in progress?

**Comment by drewnoakes** [comment]
That's right. Those tests are placeholders for the next bits to complete.
The main things pending are complex type support (see the complex-type
branch, and some changes in Pawel's fork) and collection support
(readonlylist). The data type test, missing field and default value tests
are failing on edge cases.

**Comment by andysturrock** [comment]
The data type one is interesting.  As far as I can see the MsgPack ReadInt32 function is returning true even though the value on the wire is a double.  So the score field just gets set to 0.

**Comment by drewnoakes** [comment]
The 'custom-unpacker' branch has a replacement for MsgPack.Cli (including the `ReadInt32` function) which will give the required behaviour once integrated. It also appears to be a fair bit faster in initial tests.

**Comment by andysturrock** [comment]
I think the ReadInt32 implementation in MsgPack contains a bug.  In ReadSubtreeInt32 all the switch cases of reading integer types and floating point types fall into the same statement, which casts the result to an Int32 from the out parameter integral.  However, if the actual value read was a float or double the read value will be contained in real32 or real64.  That's why the code neither throws nor rounds/truncates the value to an int.  Do you agree?

**Comment by drewnoakes** [comment]
I agree that it is strange behaviour, but it may be by design.

Even though MsgPack.Cli has 15,094 unit tests (!), changing the switch to use `real32` and `real64` doesn't cause them to fail. So it's not clear what the original designer's intention was.

It's possible that the user is expected to interrogate the next value's type before calling this function, in which case returning zero triggers alarm bells rather than losing precision. These unpacker methods *almost* fit the C# `bool TryGetThing(out Thing value)` pattern, but seem only to return false when the message ends. The unpacker API in the _custom-unpacker_ branch (`TryReadInt32` [usage](https://github.com/drewnoakes/msgpack-strict/blob/custom-unpacker/MsgPack.Strict.Tests/MsgPackUnpackerTests.cs#L61) and [implementation](https://github.com/drewnoakes/msgpack-strict/blob/custom-unpacker/MsgPack.Strict/MsgPackUnpacker.cs#L107)) returns false if the type cannot be converted.

A flag could be added in cases where you want conversion/coercion. I doubt I'd use this behaviour myself, though maybe there's a valid use case I can't see. Either way, returning `true` and `0` seems strange to me, but it's there and people use it. Maybe ask the question on their issue tracker. If I was the owner of that project though, I'd be scared to change it and break clients building serious systems. Quick way to lose users. They actually did that once recently with `DateTime` representation, which should really have been hidden behind an option or with assisted migration by making the current API obsolete.

**Comment by drewnoakes** [comment]
All unit tests are now passing.
